
name: 'Godot Engine 4.x Web Export'
description: 'Godot Engine 4.x Web export'
author: 'Simon Dalvai @dulvui'
branding:
  color: blue
  icon: upload-cloud

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  output-file-path:
    description: 'Path of the exported html files'
    required: false
    default: 'html5/index.html'
  create-export-preset-cfg:
    description: 'Set true if a simple export_presets.cfg should be created'
    required: false
    default: true
  godot-version:
    description: 'Godot Engine version. Supported are 4.x versions'
    required: false
    default: '4.2'
  os:
    description: 'The runners OS. Linux and Windows supported'
    required: false
    default: 'Linux'
  
runs:
  using: "composite"
  steps:
    # - name: Check is running on Linux
    #   if: runner.os != 'Linux'
    #   shell: bash
    #   run: exit 1

    - name: Define OS_SUFFIX
      shell: bash
      run: |
        [[ "Linux" = ${{ inputs.os }} ]] && echo "OS_SUFFIX=linux_headless.64" >> $GITHUB_ENV
        [[ "Windows" = ${{ inputs.os }} ]] && echo "OS_SUFFIX=win64.exe" >> $GITHUB_ENV

    - name: Define TEMPLATE_DIR
      shell: bash
      run: |
        [[ "Linux" = ${{ inputs.os }} ]] && echo "TEMPLATE_DIR=~/.local/share/godot/export_templates/${{ inputs.godot-version }}.stable" >> $GITHUB_ENV
        [[ "Windows" = ${{ inputs.os }} ]] && echo "TEMPLATE_DIR=C:/Users/runneradmin/AppData/Roaming/Godot/export_templates/${{ inputs.godot-version }}.stable" >> $GITHUB_ENV

    - name: Create export presets config
      if: ${{ inputs.create-export-preset-cfg  == 'true' }}
      shell: bash
      run: cp D:/a/_actions/dulvui/godot-4-html-export/v0.0.2/export_presets.cfg ${{ inputs.working-directory }}/export_presets.cfg

    - name: Create export paths directory structure
      shell: bash
      run: mkdir -p "$(dirname ${{ inputs.output-file-path }})"

    # - name: Cache Godot files
    #   id: cache-godot
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       ~/.local/share/godot/**
    #       /usr/local/bin/godot
    #       ~/.config/godot/**
    #     key: ${{ runner.os }}-godot-${{ inputs.godot-version }}

    - name: Install wget on Windows
      shell: bash
      if: runner.os == 'Windows'
      run: choco install wget --no-progress 

    - name: Download and config Godot Engine linux server and templates
      shell: bash
      if: steps.cache-godot.outputs.cache-hit != 'true'
      run: |
        wget -q https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_${{ env.OS_SUFFIX }}.zip
        wget -q https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        unzip Godot_v${{ inputs.godot-version }}-stable_${{ env.OS_SUFFIX }}.zip
        unzip Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        mkdir -p ${{ env.TEMPLATE_DIR }}
        mv templates/* ${{ env.TEMPLATE_DIR }}
        rm -f Godot_v${{ inputs.godot-version }}-stable_${{ env.OS_SUFFIX }}.zip Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz



    - name: Export Godot project to html
      shell: bash
      run: ./Godot_v${{ inputs.godot-version }}-stable_${{ env.OS_SUFFIX }} --headless --path ${{ inputs.working-directory }} --export-release Web ${{ inputs.output-file-path }}
